---
title: "Data-processing"
output: github_document
---

This file takes in Excel data copied from the Army Corps of Engineers website and turns it into cleaned .Rmd files. The data looks at openings of the Bonnet Carre spillway and associated water flows.

#Libraries and parameters
```{r}
# loading relevant packages
library(tidyverse)
library(readxl)
library(lubridate)
```

```{r}
#loading file names from where they are saved in my local machine. If you want this code to run on your local machine, you must either: 1. create the exact following file structure under your Home, and clone the git repository to that directory, or 2. change each of these file names when running the program on your local machine.
file_2019_opening1 <- "~/Autumn-2019/COMM177b/rising-waters/2019-Opening1.xlsx"
file_2019_opening2 <- "~/Autumn-2019/COMM177b/rising-waters/2019-Opening2.xlsx"
file_2018_opening1 <- "~/Autumn-2019/COMM177b/rising-waters/2018-Opening1.xlsx"
file_2016_opening1 <- "~/Autumn-2019/COMM177b/rising-waters/2016-Opening1.xlsx"

# paths for saving the new .Rds (R data files) for easier manipulation
path_opening1_2019 <- "~/Autumn-2019/COMM177b/rising-waters/2019-Opening1.Rds"
path_opening2_2019 <- "~/Autumn-2019/COMM177b/rising-waters/2019-Opening2.Rds"
path_opening1_2018 <- "~/Autumn-2019/COMM177b/rising-waters/2018-Opening1.Rds"
path_opening1_2016 <- "~/Autumn-2019/COMM177b/rising-waters/2016-Opening1.Rds"
```

#Load data
```{r}
#this loads the raw data from their file names
raw_2019_opening1 <- read_excel(file_2019_opening1)

raw_2019_opening2 <- read_excel(file_2019_opening2)

raw_2018_opening1 <- read_excel(file_2018_opening1)

raw_2016_opening1 <- read_excel(file_2016_opening1)
```


#Modify data tables for easier future editing
```{r}
#adjusts the 2019-opening-1 data to correct for type, unit, and grammatical errors
fixed_2019_opening1 <- 
  raw_2019_opening1 %>%
  
  # rename rows for consistency across data sets
  rename("days_open" = Day, "date" = Date, "bays_opened" = `Bays Opened`, "total_opened" = `Total Opened`, "discharge" = Discharge) %>% 
  
  #extract the first "word" from discharge column to remove units
  mutate(discharge = word(discharge, 1), year = 2019) %>% 
  
  #separate the date and recombine with the year in order to cast the date into a more usable "date" data type
  separate(date, into = c("month", "day_of_month"), sep = ". ") %>% 
  mutate(month = if_else(month == "Arp", "Apr", month)) %>% #adjust wrongly inputted data fields
  unite(col = "date", month, day_of_month, year, sep = " ") %>% 
  mutate(date = mdy(date)) %>% 
  
  #turn discharge column into a numeric value (rather than string) for easier plotting
  mutate(discharge = as.numeric(sub(",", "", discharge))) %>% 
  
  #add column to identify which opening
  mutate(opening_id = "2019-1")

```

```{r}
##adjusts the 2019-opening-1 data to correct for type, unit, and grammatical errors
fixed_2019_opening2 <- 
  raw_2019_opening2 %>% 
  rename("days_open" = Day, "date" = Date, "bays_opened" = `Bays Opened`, "total_opened" = `Total Opened`, "discharge" = Discharge)  %>% 
  
  # change date to be in "Date" format
  mutate(date = as_date(date)) %>% 

  #extract the first "word" from discharge column to remove units
  mutate(discharge = word(discharge, 1)) %>% 

 #turn discharge column into a numeric value (rather than string) for easier plotting
  mutate(discharge = as.numeric(sub(",", "", discharge))) %>% 

  #add column to identify which opening
  mutate(opening_id = "2019-2")



```

```{r}
##adjusts the 2018-opening-1 data to correct for type, unit, and grammatical errors
fixed_2018_opening1 <- 
  raw_2018_opening1 %>%
  
  # rename rows for consistency across data sets
  rename("days_open" = Day, "date" = Date, "bays_opened" = `Bays Opened`, "total_opened" = `Total Opened`, "discharge" = Discharge) %>% 
  
  #extract the first "word" from discharge column to remove units
  mutate(discharge = word(discharge, 1), year = 2018) %>% 
  
  #separate the date and recombine with the year in order to cast the date into a more usable "date" data type
  separate(date, into = c("month", "day_of_month"), sep = ". ") %>% 
  mutate(month = if_else(month == "Arp", "Apr", month)) %>% #adjust wrongly inputted data fields
  unite(col = "date", month, day_of_month, year, sep = " ") %>% 
  mutate(date = mdy(date)) %>% 
  
  #turn discharge column into a numeric value (rather than string) for easier plotting
  mutate(discharge = as.numeric(sub(",", "", discharge))) %>% 
  
  #add column to identify which opening
  mutate(opening_id = "2018-1")

```

```{r}
##adjusts the 2016-opening-1 data to correct for type, unit, and grammatical errors
fixed_2016_opening1 <- 
  raw_2016_opening1 %>%
  
  # rename rows for consistency across data sets
  rename("days_open" = Day, "date" = Date, "bays_opened" = `Bays Opened`, "total_opened" = `Total Opened`, "discharge" = CFS) %>%
  
  #extract the first "word" from discharge column to remove units
  mutate(discharge = word(discharge, 1), year = 2016) %>% 
  
  #separate the date and recombine with the year in order to cast the date into a more usable "date" data type
  separate(date, into = c("month", "day_of_month"), sep = ". ") %>% 
  mutate(month = if_else(month == "Arp", "Apr", month)) %>% 
  unite(col = "date", month, day_of_month, year, sep = " ") %>% 
  mutate(date = mdy(date)) %>% 
  
  #turn discharge, total_opened, and bays_opened columns into a numeric value (rather than string) for easier plotting,
  mutate(discharge = as.numeric(sub(",", "", discharge)), total_opened = as.numeric(total_opened), bays_opened = as.numeric(bays_opened)) %>% 
  mutate(discharge = if_else(is.na(discharge), 0, discharge)) %>% 
  
  #add column to identify which opening
  mutate(opening_id = "2016-1")


```



```{r}

str(fixed_2019_opening1)
str(fixed_2019_opening2)
str(fixed_2018_opening1)
str(fixed_2016_opening1)
```

#Put data in .Rds format for future manipulations
```{r}
#Write each fixed data frame to an R data file (paths are defined in parameters above)
write_rds(fixed_2019_opening1, path = path_opening1_2019)
write_rds(fixed_2019_opening2, path = path_opening2_2019)
write_rds(fixed_2018_opening1, path = path_opening1_2018)
write_rds(fixed_2016_opening1, path = path_opening1_2016)
```

